name: Perpetual-Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , develop]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  petpetual-actions-template-github-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "The job was automatically tiggered by a ${{ github.event_name }} event."
      - run: echo "This job is now runnning on a  ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."


      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check our repository code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: echo "The repository ${{ github.repository }} has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      # Runs a set of commands using the runners shell
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is '${{ job.status }}'"
